#!/usr/bin/env bash

# OS X Yosemite settings

# Allow disabling of internal MacBook screen when connected to an internal
# display. To use, connect external monitor, restart, close MacBook lid until
# the login screen appears, then open the lid.
#
# To undo this setting, run:
#
# sudo nvram -d boot-args
#
sudo nvram boot-args=niog=1

# Change LocalHostName to value specified by $LOCALHOSTNAME in ~/.localhostname.
# WARNING: DO NOT SET HostName, see http://apple.stackexchange.com/questions/30552/os-x-computer-name-not-matching-what-shows-on-terminal.
if [ -f ~/.localhostname ]; then
  . ~/.localhostname
  sudo scutil --set LocalHostName "$LOCALHOSTNAME"
  dscacheutil -flushcache
fi

# Change ComputerName to value specified by $COMPUTERNAME in ~/.computername.
if [ -f ~/.computername ]; then
  . ~/.computername
  sudo scutil --set ComputerName "$COMPUTERNAME"
  dscacheutil -flushcache
fi

# Show full file path in Finder title bar.
#
# To undo this setting, run:
#
# defaults write com.apple.finder _FXShowPosixPathInTitle -bool false
#
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Prevent creation of .DS_Store files on network drives.
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

# Make sure any changes update immediately by restarting Finder.
sudo killall -KILL Finder

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Performance Optimizations (Mainly for older Mac's):

# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Disable hibernation (speeds up entering sleep mode)
sudo pmset -a hibernatemode 0

# Finder: Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

# Disable focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Disable send and reply animations in Mail.app
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true
