#!/usr/bin/env bash

# MacOS High Sierra settings

[[ -v $COMPUTERNAME ]] && sudo scutil --set ComputerName "$COMPUTERNAME"
[[ -v $LOCALHOSTNAME ]] && sudo scutil --set LocalHostName "$LOCALHOSTNAME"
[[ -v $HOSTNAME ]] && sudo scutil --set HostName "$HOSTNAME"

# Flush the DNS cache if we set any of these 3 names.
[[ -v "$COMPUTERNAME" || -v  "$LOCALHOSTNAME" || -v  "$HOSTNAME" ]] && dscacheutil -flushcache

# Show full file path in Finder title bar.
#
# To undo this setting, run:
#
# defaults write com.apple.finder _FXShowPosixPathInTitle -bool false
#
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Prevent creation of .DS_Store files on network drives.
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

# Make sure any changes update immediately by restarting Finder.
sudo killall -KILL Finder

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Performance Optimizations (Mainly for older Mac's):

# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Disable hibernation (speeds up entering sleep mode)
sudo pmset -a hibernatemode 0

# Finder: Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Don’t animate opening applications from the Dock
defaults write com.apple.dock launchanim -bool false

# Disable focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Disable send and reply animations in Mail.app
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true
