#!/bin/bash

# OS X Yosemite settings

# Allow disabling of internal MacBook screen when connected to an internal
# display. To use, connect external monitor, restart, close MacBook lid until
# the login screen appears, then open the lid.
#
# To undo this setting, run:
#
# sudo nvram -d boot-args
#
sudo nvram boot-args=niog=1

# Change LocalHostName to value specified by $LOCALHOSTNAME in ~/.localhostname.
# WARNING: DO NOT SET HostName, see http://apple.stackexchange.com/questions/30552/os-x-computer-name-not-matching-what-shows-on-terminal.
if [ -f ~/.localhostname ]; then
  . ~/.localhostname
  sudo scutil --set LocalHostName "$LOCALHOSTNAME"
  dscacheutil -flushcache
fi

# Change ComputerName to value specified by $COMPUTERNAME in ~/.computername.
if [ -f ~/.computername ]; then
  . ~/.computername
  sudo scutil --set ComputerName "$COMPUTERNAME"
  dscacheutil -flushcache
fi

# Show full file path in Finder title bar.
#
# To undo this setting, run:
#
# defaults write com.apple.finder _FXShowPosixPathInTitle -bool false
#
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Make sure any changes update immediately by restarting Finder.
sudo killall -KILL Finder
